#!/usr/bin/env bash
set -e

ORG_PATH="github.com/redhat-nfvpe"
REPO_PATH="${ORG_PATH}/kokotap"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GO15VENDOREXPERIMENT=1
export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

echo "Building plugins"
go build "$@" ${REPO_PATH}/cmd/kokotap
